### ISSUE TITLE
skill_xp_multiplier effect produces console warn without ecoskills installed

### ISSUE THREAD

**Issue by KermX** [Auxilor/EcoItems#22]
**Describe the bug**
skill_xp_multiplier effect produces console warn without ecoskills installed

**To Reproduce**
1. have ecoitems installed with mcmmo and without ecoskills
2. create an item using the skill_xp_multiplier effect
3. select and deselect the item in your hotbar (doesn't happen every time but happens fairly regularly)

**Expected behavior**
No warn, the description of the skill_xp_muliplier effect says it should work with mcmmo

**Screenshots**
[20:12:27 WARN]: [EcoItems] Task #43497923 for EcoItems v3.27.0 generated an exception
java.lang.NoClassDefFoundError: com/willfp/ecoskills/skills/Skills
        at com.willfp.ecoitems.libreforge.integrations.ecoskills.EffectSkillXpMultiplier.handleDisable(EffectSkillXpMultiplier.kt:60) ~[EcoItems v3.27.0.jar:?]
        at com.willfp.ecoitems.libreforge.effects.Effect.disableForPlayer(Effect.kt:171) ~[EcoItems v3.27.0.jar:?]
        at com.willfp.ecoitems.libreforge.LibReforgeUtils.updateEffects(LibReforge.kt:281) ~[EcoItems v3.27.0.jar:?]
        at com.willfp.ecoitems.libreforge.LibReforgeUtils.updateEffects$default(LibReforge.kt:206) ~[EcoItems v3.27.0.jar:?]
        at com.willfp.ecoitems.items.ItemListener.onHoldItem$lambda-0(ItemListener.kt:18) ~[EcoItems v3.27.0.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.willfp.ecoskills.skills.Skills
        ... 13 more

**Server Information (please complete the following information):**
- Version: Paper version git-Paper-187 (MC: 1.18.1)
- Version of eco: eco version 6.24.2
- Version of plugin: EcoItems version 3.27.0

**Additional context**
Warn appears at seemingly random intervals when holding the item
May be an issue in other eco plugins when using the skill_xp_muliplier effect

**Comment by WillFP** [comment]
Fix coming in next update
