### ISSUE TITLE
Oraxen integration doesn’t works at EcoItems initialize process.

### ISSUE THREAD

**Issue by SundOfficial** [Auxilor/EcoItems#76]
**Describe the bug**
When configuring the plug-in without restarting the server for the first time, it recognized correctly the Oraxen items.

After restarting the server, EcoItems would not even start and gives an Oraxen error while initializing. 

**To Reproduce**
1. Configure new elements using Oraxen items.
2. Save and restart the server.
3. Scroll down to EcoItems initialize process.

**Expected behavior**
Plug-in would start without any problem and recipes using Oraxen would appear correctly.

**Screenshots**

[09:47:44] [Server thread/ERROR]: Error occurred while enabling EcoItems v3.90.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "io.th0rgal.oraxen.items.OraxenItems.map" is null
	at io.th0rgal.oraxen.items.OraxenItems.entryStream(OraxenItems.java:141) ~[oraxen-1.137.0.jar:?]
	at io.th0rgal.oraxen.items.OraxenItems.getOptionalItemById(OraxenItems.java:59) ~[oraxen-1.137.0.jar:?]
	at io.th0rgal.oraxen.items.OraxenItems.getItemById(OraxenItems.java:63) ~[oraxen-1.137.0.jar:?]
	at com.willfp.eco.internal.spigot.integrations.customitems.CustomItemsOraxen$OraxenProvider.provideForKey(CustomItemsOraxen.kt:22) ~[eco-6.38.2-all.jar:?]
	at com.willfp.eco.core.items.Items.doParse(Items.java:233) ~[eco-6.38.2-all.jar:?]
	at com.willfp.eco.core.items.ItemsLookupHandler.parse(ItemsLookupHandler.java:31) ~[eco-6.38.2-all.jar:?]
	at com.willfp.eco.core.items.ItemsLookupHandler.parse(ItemsLookupHandler.java:14) ~[eco-6.38.2-all.jar:?]
	at com.willfp.eco.core.lookup.LookupHandler.parseKey(LookupHandler.java:36) ~[eco-6.38.2-all.jar:?]
	at com.willfp.eco.core.items.Items.lookup(Items.java:193) ~[eco-6.38.2-all.jar:?]
	at com.willfp.eco.core.recipe.Recipes.createAndRegisterRecipe(Recipes.java:122) ~[eco-6.38.2-all.jar:?]
	at com.willfp.ecoitems.items.EcoItem.<init>(EcoItem.kt:60) ~[EcoItems v3.90.0.jar:?]
	at com.willfp.ecoitems.items.EcoItems.update(EcoItems.kt:57) ~[EcoItems v3.90.0.jar:?]
	at com.willfp.ecoitems.EcoItemsPlugin.handleEnableAdditional(EcoItemsPlugin.kt:31) ~[EcoItems v3.90.0.jar:?]
	at com.willfp.ecoitems.libreforge.LibReforgePlugin.handleEnable(LibReforge.kt:112) ~[EcoItems v3.90.0.jar:?]
	at com.willfp.eco.core.EcoPlugin.onEnable(EcoPlugin.java:414) ~[eco-6.38.2-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:47:44] [Server thread/INFO]: [EcoItems] Disabling EcoItems v3.90.0
[09:47:44] [Server thread/INFO]: [EcoItems] Cleaning up...

**Server Information (please complete the following information):**
- Version: [paper-1.18.2.jar:git-Paper-386]
- Version of plugin and eco: EcoItems: 3.90.0 | Eco: 6.38.2 | Oraxen: 1.137.0

**Additional context**
A turnaround for now is to use Oraxen recipes manager, but it is a little bit bizarre.

**Comment by SundOfficial** [comment]
One of Oraxen Devs get to the conclusion that it could happen because EcoItems is loading before Oraxen has registered the items to the server.

**Comment by MillionthOdin16** [comment]
I ran into this same issue. Can't use Oraxen items in ecoitems recipes.
