### ISSUE TITLE
check-offhand: true, error spamming

### ISSUE THREAD

**Issue by nikto0001** [Auxilor/EcoItems#85]
If check-offhand: is set to true and you pick up an ecoitems item in your other hand and hold it in your other hand it will start writing an error to the console

**To Reproduce**
1. put check-offhand: on true
2. take the ecoitems items in both hands
3. see the console

ERROR
[ERROR] .... Could not pass event PlayerItemHeldEvent to EcoItems v3.117.0

java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
at net.minecraft.world.entity.ai.attributes.AttributeInstance.addModifier(AttributeInstance.java:72) ~[?:?]
at net.minecraft.world.entity.ai.attributes.AttributeInstance.addPermanentModifier(AttributeInstance.java:84) ~[?:?]
at org.bukkit.craftbukkit.v1_19_R1.attribute.CraftAttributeInstance.addModifier(CraftAttributeInstance.java:50) ~[paper-1.19.2.jar:git-Paper-190]
at com.willfp.ecoitems.items.ItemAttributeListener.apply(ItemAttributeListener.kt:65) ~[EcoItems v3.117.0.jar:?]
at com.willfp.ecoitems.items.ItemAttributeListener.handle(ItemAttributeListener.kt:19) ~[EcoItems v3.117.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor164.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-190]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCarriedItem(ServerGamePacketListenerImpl.java:2183) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:24) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.a(ServerboundSetCarriedItemPacket.java:10) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-190]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[WARNING] .... [EcoItems] Task #1145 for EcoItems v3.117.0 generated an exception
java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
at net.minecraft.world.entity.ai.attributes.AttributeInstance.addModifier(AttributeInstance.java:72) ~[?:?]
at net.minecraft.world.entity.ai.attributes.AttributeInstance.addPermanentModifier(AttributeInstance.java:84) ~[?:?]
at org.bukkit.craftbukkit.v1_19_R1.attribute.CraftAttributeInstance.addModifier(CraftAttributeInstance.java:50) ~[paper-1.19.2.jar:git-Paper-190]
at com.willfp.ecoitems.items.ItemAttributeListener.apply(ItemAttributeListener.kt:65) ~[EcoItems v3.117.0.jar:?]
at com.willfp.ecoitems.items.ItemAttributeListener.handle$lambda-0(ItemAttributeListener.kt:20) ~[EcoItems v3.117.0.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-190]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-190]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-190]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Server Information**
- Version: git-Paper- (MC: 1.19.2)
- Version of plugin and eco: eco 6.43.0, ecoitems: 3.117.0

**Comment by WillFP** [comment]
my mistake! will fix

**Comment by WillFP** [comment]
Fixed!
